// ─────────────────────────────────────────────────────────────────────────────
// DEMO DATA — Portal de Autoservicio Podoplus
// ─────────────────────────────────────────────────────────────────────────────

// ── Paciente demo ─────────────────────────────────────────────────────────────

export const DEMO_PATIENT = {
  id:           "pat_001",
  firstName:    "María",
  lastName:     "Quispe Flores",
  fullName:     "María Quispe Flores",
  initials:     "MQ",
  phone:        "+51 987 654 321",
  dni:          "72345678",
  email:        "maria.quispe@gmail.com",
  birthDate:    "1988-03-15",
  birthLabel:   "15 de marzo, 1988",
  age:          38,
  bloodType:    "O+",
  address:      "Av. Primavera 1345, San Borja, Lima",
  joinedAt:     "Enero 2024",
  avatarColor:  "#7c3aed",
  totalVisits:  12,
};

// ── Plan activo ───────────────────────────────────────────────────────────────

export const DEMO_ACTIVE_PLAN = {
  id:            "plan_std",
  name:          "Plan Estándar",
  sessions:      8,
  sessionsUsed:  5,
  sessionsLeft:  3,
  expiresAt:     "1 de agosto, 2026",
  priceMonthly:  480,
  isActive:      true,
  color:         "#7c3aed",
};

// ── Sedes ─────────────────────────────────────────────────────────────────────

export const DEMO_BRANCHES = [
  {
    id:       "br_sanborja",
    name:     "Podoplus San Borja",
    address:  "Av. Primavera 1345, San Borja",
    district: "San Borja",
    phone:    "(01) 234-5678",
    hours:    "Lun–Sáb: 8:00 am – 7:00 pm",
    mapUrl:   "https://maps.google.com",
    isFavorite: true,
    distance: "1.2 km",
    rating:   4.8,
  },
  {
    id:       "br_miraflores",
    name:     "Podoplus Miraflores",
    address:  "Av. Larco 740, Miraflores",
    district: "Miraflores",
    phone:    "(01) 234-9900",
    hours:    "Lun–Sáb: 9:00 am – 6:00 pm",
    mapUrl:   "https://maps.google.com",
    isFavorite: false,
    distance: "4.5 km",
    rating:   4.9,
  },
  {
    id:       "br_lamolina",
    name:     "Podoplus La Molina",
    address:  "Av. La Fontana 890, La Molina",
    district: "La Molina",
    phone:    "(01) 235-1100",
    hours:    "Lun–Vie: 9:00 am – 6:00 pm",
    mapUrl:   "https://maps.google.com",
    isFavorite: false,
    distance: "8.1 km",
    rating:   4.7,
  },
];

// ── Servicios ─────────────────────────────────────────────────────────────────

export const DEMO_SERVICES = [
  {
    id:              "svc_general",
    name:            "Podología General",
    description:     "Limpieza, corte y cuidado general del pie. Incluye revisión de uñas y callosidades.",
    duration:        45,
    price:           80,
    color:           "#7c3aed",
    emoji:           "🦶",
    category:        "General",
    allowSelfService: true,
  },
  {
    id:              "svc_hongos",
    name:            "Tratamiento de Hongos",
    description:     "Diagnóstico y tratamiento de onicomicosis y micosis cutánea. Seguimiento personalizado.",
    duration:        60,
    price:           120,
    color:           "#0891b2",
    emoji:           "🔬",
    category:        "Tratamientos",
    allowSelfService: true,
  },
  {
    id:              "svc_diabetico",
    name:            "Pie Diabético",
    description:     "Atención especializada para pacientes con diabetes. Revisión vascular y neurológica.",
    duration:        60,
    price:           150,
    color:           "#dc2626",
    emoji:           "💉",
    category:        "Especialidad",
    allowSelfService: true,
  },
  {
    id:              "svc_quiropodia",
    name:            "Quiropodia",
    description:     "Tratamiento de callos, helomas y durezas. Resultados visibles desde la primera sesión.",
    duration:        45,
    price:           90,
    color:           "#16a34a",
    emoji:           "✂️",
    category:        "General",
    allowSelfService: true,
  },
];

// ── Citas ─────────────────────────────────────────────────────────────────────

export const DEMO_APPOINTMENTS = [
  {
    id:          "appt_001",
    serviceId:   "svc_general",
    serviceName: "Podología General",
    serviceColor: "#7c3aed",
    branchId:    "br_sanborja",
    branchName:  "Podoplus San Borja",
    specialist:  "Dra. Carmen Salinas",
    date:        "2026-04-24",
    dateLabel:   "Jueves, 24 de abril",
    time:        "10:00",
    timeLabel:   "10:00 am",
    duration:    45,
    status:      "confirmed",
    statusLabel: "Confirmada",
    price:       80,
    notes:       "",
    isUpcoming:  true,
  },
  {
    id:          "appt_002",
    serviceId:   "svc_hongos",
    serviceName: "Tratamiento de Hongos",
    serviceColor: "#0891b2",
    branchId:    "br_sanborja",
    branchName:  "Podoplus San Borja",
    specialist:  "Dra. Carmen Salinas",
    date:        "2026-03-27",
    dateLabel:   "Viernes, 27 de marzo",
    time:        "11:00",
    timeLabel:   "11:00 am",
    duration:    60,
    status:      "completed",
    statusLabel: "Completada",
    price:       120,
    notes:       "Seguimiento de tratamiento antifúngico.",
    isUpcoming:  false,
  },
  {
    id:          "appt_003",
    serviceId:   "svc_general",
    serviceName: "Podología General",
    serviceColor: "#7c3aed",
    branchId:    "br_miraflores",
    branchName:  "Podoplus Miraflores",
    specialist:  "Dr. Luis Paredes",
    date:        "2026-03-06",
    dateLabel:   "Viernes, 6 de marzo",
    time:        "09:30",
    timeLabel:   "9:30 am",
    duration:    45,
    status:      "completed",
    statusLabel: "Completada",
    price:       80,
    notes:       "",
    isUpcoming:  false,
  },
  {
    id:          "appt_004",
    serviceId:   "svc_quiropodia",
    serviceName: "Quiropodia",
    serviceColor: "#16a34a",
    branchId:    "br_sanborja",
    branchName:  "Podoplus San Borja",
    specialist:  "Dra. Carmen Salinas",
    date:        "2026-02-13",
    dateLabel:   "Viernes, 13 de febrero",
    time:        "10:00",
    timeLabel:   "10:00 am",
    duration:    45,
    status:      "completed",
    statusLabel: "Completada",
    price:       90,
    notes:       "",
    isUpcoming:  false,
  },
  {
    id:          "appt_005",
    serviceId:   "svc_general",
    serviceName: "Podología General",
    serviceColor: "#7c3aed",
    branchId:    "br_sanborja",
    branchName:  "Podoplus San Borja",
    specialist:  "Dra. Carmen Salinas",
    date:        "2026-01-22",
    dateLabel:   "Jueves, 22 de enero",
    time:        "10:00",
    timeLabel:   "10:00 am",
    duration:    45,
    status:      "no_show",
    statusLabel: "No asistió",
    price:       80,
    notes:       "",
    isUpcoming:  false,
  },
];

// ── Planes disponibles ────────────────────────────────────────────────────────

export const DEMO_PLANS = [
  {
    id:           "plan_basic",
    name:         "Plan Básico",
    price:        280,
    period:       "mes",
    sessions:     4,
    color:        "#6b7280",
    gradient:     "from-slate-500 to-slate-700",
    features: [
      "4 sesiones por mes",
      "Podología General",
      "Reserva online",
      "Recordatorios por WhatsApp",
    ],
    notIncluded: [
      "Tratamientos especializados",
      "Atención prioritaria",
      "Descuentos en productos",
    ],
    isCurrent:    false,
    isPopular:    false,
  },
  {
    id:           "plan_std",
    name:         "Plan Estándar",
    price:        480,
    period:       "mes",
    sessions:     8,
    color:        "#7c3aed",
    gradient:     "from-violet-600 to-violet-800",
    features: [
      "8 sesiones por mes",
      "Todos los servicios generales",
      "Reserva online prioritaria",
      "Recordatorios por WhatsApp",
      "10% descuento en productos",
    ],
    notIncluded: [
      "Tratamientos especializados ilimitados",
      "Atención de emergencia",
    ],
    isCurrent:    true,
    isPopular:    true,
  },
  {
    id:           "plan_premium",
    name:         "Plan Premium",
    price:        680,
    period:       "mes",
    sessions:     12,
    color:        "#b45309",
    gradient:     "from-amber-600 to-amber-800",
    features: [
      "12 sesiones por mes",
      "Todos los servicios",
      "Tratamientos especializados",
      "Atención prioritaria 24h",
      "20% descuento en productos",
      "Atención a domicilio (1 vez/mes)",
    ],
    notIncluded: [],
    isCurrent:    false,
    isPopular:    false,
  },
];
